# Generated by Django 2.2 on 2019-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('food', 'Food'), ('it', 'IT'), ('psycho', 'Psychology'), ('bikes', 'Bikes')], default='other', max_length=20),
        ),
    ]
